[package]
name = "chudnovsky"
version = "0.1.0"
authors = ["Joris Vankerschaver <joris.vankerschaver@gmail.com>"]
edition = "2018"

[dependencies]
rug = "1.7"

[lib]
name = "chudnovsky"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.9.0"
features = ["extension-module"]
